CREATE TABLE IF NOT EXISTS views (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ip_date_hash VARCHAR,
	visit_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	page VARCHAR,
	referer VARCHAR NULLABLE,
	browser_agent VARCHAR NULLABLE
);