CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	time DATETIME DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR NULLABLE,
  website VARCHAR NULLABLE,
  name VARCHAR NULLABLE,
  pending BOOLEAN DEFAULT TRUE,
  canvas_data BLOB NULLABLE
);
